# Generated by Django 5.2.1 on 2025-05-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('access', models.CharField(choices=[('any', 'Anyone'), ('email_required', 'Email Required')], default='any', max_length=25)),
                ('status', models.CharField(choices=[('published', 'Published'), ('soon', 'Soon'), ('draft', 'Draft')], default='draft', max_length=25)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
