# Generated by Django 5.2.1 on 2025-05-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_created_at_course_public_id_course_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='public_id',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
