# Generated by Django 5.2.1 on 2025-05-30 06:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverificationevent',
            old_name='exprired_at',
            new_name='expired_at',
        ),
        migrations.AddField(
            model_name='email',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailverificationevent',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
